# Modifed from https://github.com/flathub/net.veloren.veloren/raw/master/net.veloren.veloren.yaml

name: Auto update

env:
  BUILDER_TOOLS_URL: https://github.com/catsout/flatpak-builder-tools.git
  BUILDER_TOOLS_BRANCH: master

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          set -e
          sudo apt install python3-toml python3-aiohttp

      - uses: actions/checkout@v2

      - name: Download flatpak-builder-tools
        run: |
          git clone -b ${BUILDER_TOOLS_BRANCH} \
                       ${BUILDER_TOOLS_URL} \
                       builder-tools

      - name: Run update
        run: |
          set -e
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "Workflow trigger"
          python3 ./update.py standardnotes-git.json --generator-script-url https://github.com/flatpak/flatpak-builder-tools/raw/master/node/flatpak-node-generator.py --generator-arg=--electron-node-headers --generator-arg=--xdg-layout --generator-arg=-r --generator-arg=yarn --generator-arg=yarn.lock
          git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
